steps:
  - name: node:10.15.1
    entrypoint: yarn
    args: ['--cwd', 'packages/bundler', 'install']
    waitFor: ['-']
    id: 'bundler-install'
  - name: node:10.15.1
    entrypoint: yarn
    args: ['--cwd', 'packages/bundler', 'build:dev']
  - name: gcr.io/cloud-builders/gsutil
    args: [
      '-m',
      '-h',
      'Cache-Control:public, max-age=60',
      'cp',
      '-r',
      'packages/bundler/dist/.',
      'gs://firedup-dev-assets'
    ]
timeout: "1600s"
options:
  machineType: 'N1_HIGHCPU_8'
